source 'https://github.com/CocoaPods/Specs.git'
project 'JSwiftQMessages.xcodeproj'
platform :ios, '9.0'
# We have to have this line because we use swift.
use_frameworks!

target 'JSwiftQMessages' do
pod 'JSQMessagesViewController'
end

target 'JSwiftQMessagesTests' do

end

target 'JSwiftQMessagesUITests' do

end

